### ISSUE TITLE
Fix or workaround a crash in `rtm_read()`

### ISSUE THREAD

**Issue by julianoes** [julianoes/hangrybot#22]
This happened:
```
Traceback (most recent call last):
  File "./hangrybot.py", line 171, in <module>
    main()
  File "./hangrybot.py", line 167, in main
    bot.run()
  File "./hangrybot.py", line 38, in run
    self.slack_client.rtm_read())
  File "/home/ubuntu/.local/lib/python3.5/site-packages/slackclient/client.py", line 135, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/slackclient/server.py", line 194, in websocket_safe_read
    data += "{0}\n".format(self.websocket.recv())
  File "/home/ubuntu/.local/lib/python3.5/site-packages/websocket/_core.py", line 300, in recv
    opcode, data = self.recv_data()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/websocket/_core.py", line 317, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/websocket/_core.py", line 330, in recv_data_frame
    frame = self.recv_frame()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/websocket/_core.py", line 364, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/websocket/_abnf.py", line 361, in recv_frame
    self.recv_header()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/websocket/_abnf.py", line 309, in recv_header
    header = self.recv_strict(2)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/websocket/_abnf.py", line 396, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/home/ubuntu/.local/lib/python3.5/site-packages/websocket/_core.py", line 434, in _recv
    return recv(self.sock, bufsize)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/websocket/_socket.py", line 94, in recv
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
```

**Comment by julianoes** [comment]
Fixed by #23 and eventually #27.
